/**
 * generated by Xtext 2.31.0
 */
package tau.smlab.syntech.spectra;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Regexp Test</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link tau.smlab.syntech.spectra.RegexpTest#getName <em>Name</em>}</li>
 *   <li>{@link tau.smlab.syntech.spectra.RegexpTest#getRegExpPointer <em>Reg Exp Pointer</em>}</li>
 *   <li>{@link tau.smlab.syntech.spectra.RegexpTest#getRegExp <em>Reg Exp</em>}</li>
 * </ul>
 *
 * @see tau.smlab.syntech.spectra.SpectraPackage#getRegexpTest()
 * @model
 * @generated
 */
public interface RegexpTest extends Decl
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see tau.smlab.syntech.spectra.SpectraPackage#getRegexpTest_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link tau.smlab.syntech.spectra.RegexpTest#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Reg Exp Pointer</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reg Exp Pointer</em>' reference.
   * @see #setRegExpPointer(DefineRegExpDecl)
   * @see tau.smlab.syntech.spectra.SpectraPackage#getRegexpTest_RegExpPointer()
   * @model
   * @generated
   */
  DefineRegExpDecl getRegExpPointer();

  /**
   * Sets the value of the '{@link tau.smlab.syntech.spectra.RegexpTest#getRegExpPointer <em>Reg Exp Pointer</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reg Exp Pointer</em>' reference.
   * @see #getRegExpPointer()
   * @generated
   */
  void setRegExpPointer(DefineRegExpDecl value);

  /**
   * Returns the value of the '<em><b>Reg Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reg Exp</em>' containment reference.
   * @see #setRegExp(RegExp)
   * @see tau.smlab.syntech.spectra.SpectraPackage#getRegexpTest_RegExp()
   * @model containment="true"
   * @generated
   */
  RegExp getRegExp();

  /**
   * Sets the value of the '{@link tau.smlab.syntech.spectra.RegexpTest#getRegExp <em>Reg Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reg Exp</em>' containment reference.
   * @see #getRegExp()
   * @generated
   */
  void setRegExp(RegExp value);

} // RegexpTest
